sbt-build = [
  "ch.epfl.scala:sbt-scalafix:0.14.9:sbt-plugin"
  "ch.epfl.scala:sbt-version-policy:3.3.0:sbt-plugin"
  "com.alejandrohdezma:sbt-ci:5.0.0:sbt-plugin"
  "com.alejandrohdezma:sbt-fix:0.13.1:sbt-plugin"
  "com.alejandrohdezma:sbt-github-header:0.15.0:sbt-plugin"
  "com.alejandrohdezma:sbt-github-mdoc:0.15.0:sbt-plugin"
  "com.alejandrohdezma:sbt-mdoc-toc:0.6.0:sbt-plugin"
  "com.alejandrohdezma:sbt-modules:0.6.0:sbt-plugin"
  "com.alejandrohdezma:sbt-scalafix-defaults:0.16.0:sbt-plugin"
  "com.alejandrohdezma:sbt-scalafmt-defaults:0.11.0:sbt-plugin"
  "com.github.sbt:sbt-ci-release:1.12.1:sbt-plugin"
  "com.github.sbt:sbt-header:5.11.0:sbt-plugin"
  "com.thoughtworks.sbt-api-mappings:sbt-api-mappings:3.0.3:sbt-plugin"
  "org.scalameta:sbt-mdoc:2.9.2:sbt-plugin"
  "org.scalameta:sbt-scalafmt:2.6.2:sbt-plugin"
  "org.typelevel:sbt-tpolecat:0.5.7:sbt-plugin"
]

common-settings {
  scala-versions = ["~2.13.18", "~3.3.8"]
}

trace4cats-kafka-client = [
  "io.janstenpickle::trace4cats-fs2:0.14.7"
  "org.typelevel::fs2-kafka:4.0.0"
  "io.janstenpickle::trace4cats-testkit:0.14.7:test"
]
