sbt-build = [
  "ch.epfl.scala:sbt-scalafix:0.14.6:sbt-plugin"
  "ch.epfl.scala:sbt-version-policy:3.2.1:sbt-plugin"
  "com.alejandrohdezma:sbt-ci:3.0.0:sbt-plugin"
  "com.alejandrohdezma:sbt-fix:0.12.0:sbt-plugin"
  "com.alejandrohdezma:sbt-github-header:0.13.0:sbt-plugin"
  "com.alejandrohdezma:sbt-github-mdoc:0.13.0:sbt-plugin"
  "com.alejandrohdezma:sbt-mdoc-toc:0.5.0:sbt-plugin"
  "com.alejandrohdezma:sbt-modules:0.5.0:sbt-plugin"
  "com.alejandrohdezma:sbt-scalafix-defaults:0.15.0:sbt-plugin"
  "com.alejandrohdezma:sbt-scalafmt-defaults:0.10.0:sbt-plugin"
  "com.github.sbt:sbt-ci-release:1.11.2:sbt-plugin"
  "com.github.sbt:sbt-header:5.11.0:sbt-plugin"
  "com.thoughtworks.sbt-api-mappings:sbt-api-mappings:3.0.2:sbt-plugin"
  "org.scalameta:sbt-mdoc:2.9.0:sbt-plugin"
  "org.scalameta:sbt-scalafmt:2.6.1:sbt-plugin"
  "org.typelevel:sbt-tpolecat:0.5.5:sbt-plugin"
]

common-settings {
  scala-versions = ["2.13.18", "3.3.7"]
}

trace4cats-kafka-client = [
  "com.github.fd4s::fs2-kafka:3.0.1"
  "io.janstenpickle::trace4cats-fs2:0.14.2"
  "io.janstenpickle::trace4cats-testkit:0.14.2:test"
]
