sbt-build = [
  "com.codecommit:sbt-github-actions:0.14.2:sbt-plugin"
  "com.github.sbt:sbt-dynver:5.0.1:sbt-plugin"
  "io.shiftleft:sbt-ci-release-early:2.0.46:sbt-plugin"
  "org.scalameta:sbt-scalafmt:2.5.2:sbt-plugin"
  "org.typelevel:sbt-tpolecat:0.5.2:sbt-plugin"
]

common-settings {
  scala-versions = ["2.13.17", "3.3.7"]
}

trace4cats-kafka-client = [
  "com.github.fd4s::fs2-kafka:3.0.1"
  "io.janstenpickle::trace4cats-fs2:0.14.2"
  "io.janstenpickle::trace4cats-testkit:0.14.2:test"
]
